# Generated by Django 6.0.3 on 2026-03-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='note_images/'),
        ),
        migrations.AddField(
            model_name='note',
            name='mode',
            field=models.CharField(choices=[('text', 'Text'), ('list', 'List')], default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(max_length=1000),
        ),
    ]
